name: personnemuette
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  # Removed tflite_flutter and camera
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.2.2
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/facebook_icon.webp